global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "tarantool"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - host.docker.internal:8081
          - host.docker.internal:8082
          - host.docker.internal:8083
          - host.docker.internal:8084
          - host.docker.internal:8085
          - host.docker.internal:8086

  - job_name: "jmx"
    metrics_path: "/"
    static_configs:
      - targets:
          - host.docker.internal:12345
