site_name: Tarantool Java SDK
copyright: Copyright ¬©Ô∏è 2025 VK Tech
repo_name: tarantool/tarantool-java-sdk
repo_url: https://github.com/tarantool/tarantool-java-sdk
site_url: https://tarantool.github.io/tarantool-java-sdk/
docs_dir: doc-src
strict: true

extra:
  language: ru
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tarantool/tarantool-java-sdk
    - icon: tarantool/tarantool
      link: https://www.tarantool.io/ru/
  version:
    provider: mike
    alias: true

plugins:
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: ru
          default: true
          link: "/"
          name: üá∑üá∫ RU
          build: true
        - locale: en
          link: "/en/"
          name: üá∫üá∏ EN
          build: true
          nav_translations:
            –ì–ª–∞–≤–Ω–∞—è: Home
            –î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è: Documentation
            –í—ã—Å–æ–∫–æ—É—Ä–æ–≤–Ω–µ–≤—ã–π –∫–ª–∏–µ–Ω—Ç: High-Level Client
            –ê—Ä—Ö–∏—Ç–µ–∫—Ç—É—Ä–∞: Architecture
            –û–¥–∏–Ω–æ—á–Ω—ã–π —É–∑–µ–ª: Single Node
            –ö–ª–∞—Å—Ç–µ—Ä TarantoolDB: TarantoolDB Cluster
            –ö–ª–∞—Å—Ç–µ—Ä TQE: TQE Cluster
            –ü—Ä–∏–º–µ—Ä—ã –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è: Usage examples
            –ü–æ–¥–∫–ª—é—á–µ–Ω–∏–µ –∫ —É–∑–ª–∞–º: Connecting to nodes
            –•—Ä–∞–Ω–∏–º—ã–µ –ø—Ä–æ—Ü–µ–¥—É—Ä—ã: Stored procedures
  - drawio:
      darkmode: true
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      # –≤ —Å–µ–∫—É–Ω–¥–∞—Ö(in seconds)
      request_timeout: 300

theme:
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.footnote.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/weather-night
    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/weather-sunny

#  favicon: images/favicon.svg
  icon:
    annotation: material/chat-question
    repo: fontawesome/brands/github
    logo: tarantool/tarantool
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

nav:
  - –ì–ª–∞–≤–Ω–∞—è:
      - index.md
  - –î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è:
      - pages/index.md
      - Spring Data:
          - pages/spring-data/index.md
          - pages/spring-data/configuration.md
          - pages/spring-data/repository.md
          - pages/spring-data/derived-methods.md
          - pages/spring-data/sort.md
          - pages/spring-data/query-lua.md
          - pages/spring-data/page-slice-pageable.md
          - pages/spring-data/scroll-api.md
      - –í—ã—Å–æ–∫–æ—É—Ä–æ–≤–Ω–µ–≤—ã–π –∫–ª–∏–µ–Ω—Ç:
          - pages/client/index.md
          - –ê—Ä—Ö–∏—Ç–µ–∫—Ç—É—Ä–∞:
              - pages/client/arch/index.md
              - pages/client/arch/high-level-arch.md
              - pages/client/arch/heartbeat.md
              - pages/client/arch/balancer.md
              - pages/client/arch/connection-pool.md
              - pages/client/arch/instance-connection-group.md
              - pages/client/arch/exception-handling.md
              - pages/client/arch/connection-to-multiple-nodes.md
              - pages/client/arch/call.md
              - pages/client/arch/tuple_pojo_mapping.md
          - –ü—Ä–∏–º–µ—Ä—ã –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è:
              - pages/client/examples/index.md
              - –ü–æ–¥–∫–ª—é—á–µ–Ω–∏–µ –∫ —É–∑–ª–∞–º:
                  - pages/client/examples/connection/index.md
                  - pages/client/examples/connection/single-node.md
                  - pages/client/examples/connection/crud-cluster.md
              - –•—Ä–∞–Ω–∏–º—ã–µ –ø—Ä–æ—Ü–µ–¥—É—Ä—ã:
                  - pages/client/examples/call/index.md
                  - pages/client/examples/call/call.md
      - Tarantool Testcontainers:
          - pages/testcontainers/index.md
          - –û–¥–∏–Ω–æ—á–Ω—ã–π —É–∑–µ–ª:
              - pages/testcontainers/single/index.md
              - pages/testcontainers/single/single-node-testcontainers-arch.md
              - pages/testcontainers/single/single-node-testcontainers-standard-impl.md
              - pages/testcontainers/single/single-node-testcontainers-standard-impl-example.md
          - –ö–ª–∞—Å—Ç–µ—Ä TarantoolDB:
              - pages/testcontainers/tdb/index.md
              - pages/testcontainers/tdb/tdb-cluster-testcontainers-arch.md
              - pages/testcontainers/tdb/tdb2-cluster-testcontainers-standard-impl.md
              - pages/testcontainers/tdb/tdb2-cluster-testcontainers-standard-impl-example.md
          - –ö–ª–∞—Å—Ç–µ—Ä TQE:
              - pages/testcontainers/tqe/index.md
              - pages/testcontainers/tqe/tqe-cluster-arch.md
              - pages/testcontainers/tqe/tqe-cluster-example.md

markdown_extensions:
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __spanz
      pygments_lang_class: true
      default_lang: java
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      base_path: doc-src/java/src
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

exclude_docs: |
  venv
  requirements.txt
  pom.xml
  README.md
