name: Prepare Release to Maven Central

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release and tag version'
        required: true
        default: "1.5.0"
      developmentVersion:
        description: 'Version to use for new working copy'
        required: true
        default: '2.0.0-SNAPSHOT'

jobs:
  release:
    runs-on: ubuntu-20.04-self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Run release release.yml
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          RELEASE_VERSION: ${{ github.event.inputs.releaseVersion }}
          DEVELOPMENT_VERSION: ${{ github.event.inputs.developmentVersion }}
        run: |
          ./mvnw release:prepare -DskipTests -Darguments=-DskipTests \
            -DreleaseVersion="$RELEASE_VERSION" -Dtag="$RELEASE_VERSION" \
            -DdevelopmentVersion="$DEVELOPMENT_VERSION"
