name: Publish Snapshot to Maven Central

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+\-dev.[0-9]+'

jobs:
  publish-snapshot:
    if: "!contains(github.event.head_commit.message, '[maven-release-plugin]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: central-portal-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_TOKEN

      - name: Publish Snapshot to Maven Central
        run: |
          ./mvnw -B clean deploy -PsonatypeSnapshot -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USER }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
